export const scottnath = {
  login: 'scottnath',
  id: 216931,
  node_id: 'MDQ6VXNlcjIxNjkzMQ==',
  // avatar_url: 'https://avatars.githubusercontent.com/u/216931?v=4',
  avatar_url: './216931.jpg',
  gravatar_id: '',
  url: 'https://api.github.com/users/scottnath',
  html_url: 'https://github.com/scottnath',
  followers_url: 'https://api.github.com/users/scottnath/followers',
  following_url: 'https://api.github.com/users/scottnath/following{/other_user}',
  gists_url: 'https://api.github.com/users/scottnath/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/scottnath/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/scottnath/subscriptions',
  organizations_url: 'https://api.github.com/users/scottnath/orgs',
  repos_url: 'https://api.github.com/users/scottnath/repos',
  events_url: 'https://api.github.com/users/scottnath/events{/privacy}',
  received_events_url: 'https://api.github.com/users/scottnath/received_events',
  type: 'User',
  site_admin: false,
  name: 'Scott Nath',
  company: 'IBM',
  blog: 'scottnath.com',
  location: 'New York',
  email: null,
  hireable: true,
  bio: 'Front-end UI DevOps architect. Efficiency in all things and productivity will follow.',
  twitter_username: null,
  public_repos: 125,
  public_gists: 24,
  followers: 9,
  following: 10,
  created_at: '2010-03-06T01:59:25Z',
  updated_at: '2023-08-02T06:01:07Z'
};