name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron:  '0 0,12 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://scottnath.com/sitemap-index.xml'
          since: 1
          since-unit: "day"
          key: ${{ secrets.INDEXNOW_KEY }}