name: 'IndexNow'
on:
  push:
    branches:
      - main

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://scottnath.com/sitemap-index.xml'
          since: 1
          since-unit: "year"
          key: ${{ secrets.INDEXNOW_KEY }}